In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv('Movie+Assignment+Data.csv')
# Write your code for importing the csv file here
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [35]:
# Write your code for inspection here
print(movies.shape)
print(movies.info())

(4996, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 4996 entries, 0 to 5042
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   director_name           4893 non-null   object
 1   num_critic_for_reviews  4947 non-null   float64
 2   gross                   4123 non-null   float64
 3   genres                  4996 non-null   object
 4   actor_1_name            4989 non-null   object
 5   movie_title             4996 non-null   object
 6   num_voted_users         4996 non-null   int64
 7   num_user_for_reviews    4975 non-null   float64
 8   language                4982 non-null   object
 9   budget                  4510 non-null   float64
 10  title_year              4889 non-null   float64
 11  imdb_score              4996 non-null   float64
 12  movie_facebook_likes    4996 non-null   int64
 13  genre_1                 4996 non-null   object
 14  genre_2                 4996 non-null   object
dtypes: float64(6), int64(2), object(7)
memory usage: 624.5+ KB
None

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here
null_percentage = (movies.isnull().sum() / len(movies)) * 100

null_percentage_rounded = null_percentage.round(2)

null_percentage_rounded

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies = movies.drop(['color', 
                      'director_facebook_likes', 
                      'actor_3_facebook_likes', 
                      'actor_1_facebook_likes', 
                      'cast_total_facebook_likes', 
                      'actor_2_facebook_likes', 
                      'duration', 
                      'facenumber_in_poster', 
                      'content_rating', 
                      'country', 
                      'movie_imdb_link', 
                      'aspect_ratio',
                      'plot_keywords',
                      'actor_2_name',
                      'actor_3_name'], 
                       axis = 1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [9]:
# Write your code for dropping the rows here

null_percentage = (movies.isnull().sum() / len(movies)) * 100
columns_drop = null_percentage[null_percentage > 5].index.tolist()
movies_cleaned_1 = movies.dropna(subset=columns_drop)

movies_cleaned_1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [10]:
# Write your code for dropping the rows here
movies_cleaned_2 = movies_cleaned_1.dropna(thresh = 8)

movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [11]:
# Write your code for filling the NaN values in the 'language' column here
movies_cleaned_2['language'] = movies_cleaned_2['language'].fillna('English')
movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [12]:
# Write your code for checking number of retained rows here
total_rows = movies.shape[0]

retained_rows = movies_cleaned_2.shape[0]

percentage_retained = (retained_rows / total_rows) * 100

percentage_retained

77.15645449137418

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [13]:
# Write your code for unit conversion here
movies_cleaned_2['budget'] = movies_cleaned_2['budget'] / 1_000_000 
movies_cleaned_2['gross'] = movies_cleaned_2['gross'] / 1_000_000  
movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [14]:
# Write your code for creating the profit column here
movies_cleaned_2['profit'] = movies_cleaned_2['gross'] - movies_cleaned_2['budget']
print(movies_cleaned_2[['budget', 'gross', 'profit']])

        budget       gross      profit
0     237.0000  760.505847  523.505847
1     300.0000  309.404152    9.404152
2     245.0000  200.074175  -44.925825
3     250.0000  448.130642  198.130642
5     263.7000   73.058679 -190.641321
...        ...         ...         ...
5033    0.0070    0.424760    0.417760
5034    0.0070    0.070071    0.063071
5035    0.0070    2.040920    2.033920
5037    0.0090    0.004584   -0.004416
5042    0.0011    0.085222    0.084122

[3891 rows x 3 columns]

In [15]:
# Write your code for sorting the dataframe here
sorted_movies = movies_cleaned_2.sort_values(by='profit', ascending=False)

sorted_movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [16]:
# Write your code to get the top 10 profiting movies here
top10 = movies.iloc[:10, ]

top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
6,Sam Raimi,392.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258000000.0,2007.0,6.2,0
7,Nathan Greno,324.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260000000.0,2010.0,7.8,29000
8,Joss Whedon,635.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250000000.0,2015.0,7.5,118000
9,David Yates,375.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250000000.0,2009.0,7.5,10000

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [17]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(subset = None, keep = 'first', inplace = True)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [18]:
# Write code for repeating subtask 2 here
movies_cleaned_2['profit'] = movies_cleaned_2['gross'] - movies_cleaned_2['budget']

sorted_movies = movies_cleaned_2.sort_values(by='profit', ascending=False)

top10 = sorted_movies.head(10)

top10 = top10.drop_duplicates()

top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [19]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250 = movies.sort_values(by = 'imdb_score', ascending = False)
IMDb_Top_250 = IMDb_Top_250.loc[IMDb_Top_250.num_voted_users > 25000]
IMDb_Top_250 = IMDb_Top_250.iloc[:250, ]
IMDb_Top_250['Rank'] = range(1,251)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Rank
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,1
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,2
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,3
2837,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,14000,4
3481,NaN,54.0,NaN,Crime|Drama|Thriller,Kirsten Dunst,Fargo,170055,173.0,English,NaN,NaN,9.0,61000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2712,Martin McDonagh,300.0,7757130.0,Comedy|Crime|Drama,Elizabeth Berrington,In Bruges,307639,513.0,English,15000000.0,2008.0,8.0,32000,246
2916,William Friedkin,304.0,204565000.0,Horror,Ellen Burstyn,The Exorcist,284252,1058.0,English,8000000.0,1973.0,8.0,18000,247
2539,Peter Weir,96.0,95860116.0,Comedy|Drama,Robin Williams,Dead Poets Society,277451,491.0,English,16400000.0,1989.0,8.0,23000,248
160,J.J. Abrams,518.0,257704099.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Star Trek,504419,1559.0,English,150000000.0,2009.0,8.0,19000,249
2607,Tom Hooper,479.0,138795342.0,Biography|Drama|History|Romance,Colin Firth,The King's Speech,503631,636.0,English,15000000.0,2010.0,8.0,64000,250

In [20]:
 # Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250.loc[IMDb_Top_250['language'] != 'English']
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Rank
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,20000,8
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,28000,21
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,11000,22
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,28000,31
3870,Raja Menon,39.0,NaN,Action|Drama|History|Thriller|War,Nimrat Kaur,Airlift,30977,178.0,Hindi,4.400000e+06,2016.0,8.5,10000,42
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,39000,46
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,0,48
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,39000,62
3685,Rakeysh Omprakash Mehra,33.0,2197331.0,Comedy|Drama|History|Romance,Anupam Kher,Rang De Basanti,70233,321.0,Hindi,NaN,2006.0,8.4,0,63
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,11000,64
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,21000,66
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,48000,71
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,43000,79
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,82
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,12000,93
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,60000,95
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,14000,97
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,13000,133
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,27000,134
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,33000,139
4160,Rajkumar Hirani,15.0,NaN,Comedy|Drama|Romance,Vidya Balan,Lage Raho Munna Bhai,27569,106.0,Hindi,1.200000e+08,2006.0,8.2,349,141
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,37000,142
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e+07,2004.0,8.1,0,146
2914,Je-kyu Kang,86.0,1110186.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e+07,2004.0,8.1,0,158
1061,Andrei Tarkovsky,144.0,NaN,Drama|Mystery|Sci-Fi,Donatas Banionis,Solaris,54057,236.0,Russian,1.000000e+06,1972.0,8.1,0,164
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,5000,165
3553,José Padilha,142.0,8060.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e+06,2007.0,8.1,11000,166
4267,Alejandro G. Iñárritu,157.0,5383834.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e+06,2000.0,8.1,11000,180
3423,Katsuhiro Ôtomo,150.0,439162.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e+09,1988.0,8.1,0,199
3344,Karan Johar,210.0,4018695.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,1.200000e+07,2010.0,8.0,27000,207
4284,Ari Folman,231.0,2283276.0,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000e+06,2008.0,8.0,0,215
3456,Vincent Paronnaud,242.0,4443403.0,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000e+06,2007.0,8.0,14000,226
4144,Walter Salles,71.0,5595428.0,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000e+06,1998.0,8.0,0,231
4897,Sergio Leone,122.0,3500000.0,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,2.000000e+05,1964.0,8.0,0,239
2739,Andrey Zvyagintsev,103.0,502028.0,Drama|Mystery|Thriller,Konstantin Lavronenko,The Return,31589,172.0,Russian,NaN,2003.0,8.0,0,240

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [21]:
# Write your code for extracting the top 10 directors here
director = movies.pivot_table(values = 'imdb_score', index = 'director_name', aggfunc = 'mean')
director = director.sort_values(by = 'imdb_score', ascending = False)
director = director.iloc[:10, ]
director

                  imdb_score
director_name
John Blanchard           9.5
Mitchell Altieri         8.7
Sadyk Sher-Niyaz         8.7
Cary Bell                8.7
Mike Mayhall             8.6
Charles Chaplin          8.6
Ron Fricke               8.5
Damien Chazelle          8.5
Raja Menon               8.5
Majid Majidi             8.5

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [22]:
# Write your code for extracting the first two genres of each movie here
movies['genres'] = movies['genres'].str.split('|')
movies['genre_1'] = movies['genres'].apply(lambda x: x[0])
movies['genre_2'] = movies['genres'].apply(lambda x : x[1] if len(x) > 1 else x[0])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
0,James Cameron,723.0,760505847.0,"[Action, Adventure, Fantasy, Sci-Fi]",CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,Action,Adventure
1,Gore Verbinski,302.0,309404152.0,"[Action, Adventure, Fantasy]",Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,Action,Adventure
2,Sam Mendes,602.0,200074175.0,"[Action, Adventure, Thriller]",Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,Action,Adventure
3,Christopher Nolan,813.0,448130642.0,"[Action, Thriller]",Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,Action,Thriller
4,Doug Walker,NaN,NaN,[Documentary],Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0,Documentary,Documentary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,"[Comedy, Drama]",Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84,Comedy,Drama
5039,NaN,43.0,NaN,"[Crime, Drama, Mystery, Thriller]",Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000,Crime,Drama
5040,Benjamin Roberds,13.0,NaN,"[Drama, Horror, Thriller]",Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16,Drama,Horror
5041,Daniel Hsia,14.0,10443.0,"[Comedy, Drama, Romance]",Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660,Comedy,Drama
5042,Jon Gunn,43.0,85222.0,[Documentary],John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,Documentary,Documentary

In [23]:
movies_by_segment = movies_by_segment = movies.groupby(['genre_1', 'genre_2'])
# Write your code for grouping the dataframe here

In [24]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = pd.DataFrame(movies_by_segment['gross'].mean()).sort_values(by = 'gross', ascending = False)
PopGenre.iloc[:5, ]

                            gross
genre_1   genre_2
Family    Sci-Fi     4.349495e+08
Adventure Sci-Fi     2.286278e+08
          Animation  1.170500e+08
          Family     1.155375e+08
Action    Adventure  1.087523e+08

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [25]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies.loc[movies.actor_1_name == 'Meryl Streep']
Meryl_Streep# Include all movies in which Meryl_Streep is the lead

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,112703470.0,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,46815748.0,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,94125426.0,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,124732962.0,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,14998070.0,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,87100000.0,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,63536011.0,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,23209440.0,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,NaN,"[Biography, Comedy, Drama, Music, Romance]",Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,41597830.0,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,29959436.0,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,20338609.0,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,NaN,[Drama],Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,Drama,Drama

In [26]:
Leo_Caprio = movies.loc[movies.actor_1_name == 'Leonardo DiCaprio']
Leo_Caprio # Include all movies in which Leo_Caprio is the lead

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
26,James Cameron,315.0,658672302.0,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,292568851.0,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,183635922.0,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,102608827.0,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,162804648.0,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,57366262.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,116866727.0,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,77679638.0,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,132373442.0,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,127968405.0,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,39380442.0,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,164435221.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,39778599.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,22877808.0,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,56876365.0,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,37304950.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,18636537.0,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,12782508.0,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,46338728.0,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance

In [27]:
Brad_Pitt =movies.loc[movies.actor_1_name == 'Brad Pitt']
Brad_Pitt # Include all movies in which Brad_Pitt is the lead

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
101,David Fincher,362.0,127490802.0,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,26871.0,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,85707116.0,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,37023395.0,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,[Drama],Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,NaN,"[Comedy, Music, Romance]",Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,Comedy,Music

In [28]:
# Write your code for combining the three dataframes here
Combined = pd.concat([Meryl_Streep, Brad_Pitt, Leo_Caprio])
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,112703470.0,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,46815748.0,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,94125426.0,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,124732962.0,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,14998070.0,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,87100000.0,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,63536011.0,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,23209440.0,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,NaN,"[Biography, Comedy, Drama, Music, Romance]",Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,41597830.0,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,29959436.0,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,20338609.0,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,NaN,[Drama],Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,Drama,Drama
101,David Fincher,362.0,127490802.0,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,26871.0,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,85707116.0,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,37023395.0,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,[Drama],Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,NaN,"[Comedy, Music, Romance]",Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,Comedy,Music
26,James Cameron,315.0,658672302.0,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,292568851.0,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,183635922.0,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,102608827.0,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,162804648.0,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,57366262.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,116866727.0,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,77679638.0,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,132373442.0,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,127968405.0,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,39380442.0,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,164435221.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,39778599.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,22877808.0,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,56876365.0,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,37304950.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,18636537.0,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,12782508.0,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,46338728.0,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance

In [29]:
# Write your code for grouping the combined dataframe here
groupe_combined = Combined.groupby('actor_1_name')

groupe_combined.size()

actor_1_name
Brad Pitt            18
Leonardo DiCaprio    21
Meryl Streep         13
dtype: int64

In [30]:
# Write the code for finding the mean of critic reviews and audience reviews here
mean_reviews = Combined.groupby('actor_1_name')[['num_critic_for_reviews', 'num_user_for_reviews']].mean()

max_critic_reviews = mean_reviews['num_critic_for_reviews'].idxmax()
max_user_reviews = mean_reviews['num_user_for_reviews'].idxmax()

print(max_critic_reviews)
print(max_user_reviews)

Leonardo DiCaprio
Leonardo DiCaprio

**Checkpoint 6:** `Leonardo` has aced both the lists!

In [ ]:
#Assignment done by Bryan Japheth Charles